### ISSUE TITLE
ekco service fails to start on server named 'server'

### ISSUE THREAD

**Issue by MikaelSmith** [replicatedhq/kURL#1010]
The ekco service fails to start if the server's hostname contains `server`. https://github.com/replicatedhq/kURL/blob/master/addons/ekco/0.8.0/reboot/startup.sh#L11 fails to identify that kubernetes is ready.

**Comment by emosbaugh** [comment]
This somehow got reverted on newer versions of ekco

https://github.com/replicatedhq/kURL/commit/30b692089d760722ccc06e439664881a340f6135

**Comment by emosbaugh** [comment]
Regression from #786
