### ISSUE TITLE
Installation URL filters User-Agent HTTP header

### ISSUE THREAD

**Issue by greenstatic** [replicatedhq/kurl#102]
Why does the installation URL only serve the bash script to HTTP requests with the User-Agent HTTP header set to `curl`?

## Steps to reproduce
```bash
# This returns the bash script
curl -v https://kurl.sh/latest | less
```
Opening `https://kurl.sh/latest` in a browser or performing a GET request using Postman returns a `404 Not Found`.

**Comment by areed** [comment]
There is a web app on `https://kurl.sh` by default. You can use `https://kurl.sh/latest?type=script` to skip the user agent sniffing and get the script.
