### ISSUE TITLE
Kotsadm addon: standard type for TLS secret

### ISSUE THREAD

**Issue by dexhorthy** [replicatedhq/kurl#132]
Right now with the kotsadm addon, kurl.sh will create a secret called `kotsadm-tls` of type `Opaque`. It would be great if this could be of type `kubernetes.io/tls` so it can be re-used in Ingress specs and other K8s tools which process Secrets of this type.

(Per @areed this was done so we can store additional TLS-related fields in the secret)

I'd like to be able to re-use these certs in any applications being managed by `kotsadm`, specifcally to integrate with the `countor` addon in this case.

There's an open question around whether kotsadm should further manage this by propagating secrets to application namespaces, but I think I'd consider that out of scope for a v1 of this.

**Comment by marccampbell** [comment]
I think we could switch the type to be the proper `kubernetes.io/tls` type to make it more reusable. The additional data is small (it's a bit to indicate if the user uploaded the cert). We likely can move this bit over to an annotation in the secret for re-use.

**Comment by dexhorthy** [comment]
annotation works for me
