### ISSUE TITLE
When installing an embedded kURL cluster in HA mode, the user should be warned if their load balancer address isn't valid.

### ISSUE THREAD

**Issue by bagel-dawg** [replicatedhq/kURL#1396]
During an install, I ran into an issue where when entering a non-RFC-1123-compliant FQDN for the load balancer address, the installer will continue happily, but will ultimately fail, referencing the RFC above.

An example non-compliant hostname could be any of the following:
1. Greater than 63 characters
2. Begins with an upper-case letter
3. Begins with a numeral
4. Begins with a hyphen

All but `#2` should result in a warning+prompt or aborting of the script. `#2` can probably be addressed by accepting the input, and regex'ing it to be all lower-case.

**Comment by emosbaugh** [comment]
resolved by https://github.com/replicatedhq/kURL/pull/1861
