### ISSUE TITLE
"Press enter to proceed" should be a flaggable option to turn off the prompt

### ISSUE THREAD

**Issue by evilmonkeyslayer** [replicatedhq/kURL#1454]
When running through something like for example ansible there shouldn't need to be any required human input prompt.

IE. On https://kurl.sh/docs/install-with-kurl/advanced-options it should be classed as "no-prompt".

Otherwise a workaround has to be done with expect or editing the install.sh script to remove the prompt.

**Comment by DanStough** [comment]
Hi @evilmonkeyslayer! All of the prompts in kurl should be on a timeout to accept the default answer after 20 seconds, so unattended installs should work fine. 

1. Are you running into a specific point in the install where this isn't the case?
2. Are you just asking to ignore the prompt all together? IMHO it's better to have this information in the logs.

**Comment by evilmonkeyslayer** [comment]
> 
> 
> Hi @evilmonkeyslayer! All of the prompts in kurl should be on a timeout to accept the default answer after 20 seconds, so unattended installs should work fine.
> 
>     1. Are you running into a specific point in the install where this isn't the case?
> 
>     2. Are you just asking to ignore the prompt all together? IMHO it's better to have this information in the logs.

Well damn, don't I feel like a fool. Here I was making workarounds for something that has a timer on it.

**Comment by DanStough** [comment]
You can also check out the installer flags here which can often control the outcome of the prompts in advance: https://kurl.sh/docs/install-with-kurl/advanced-options
