### ISSUE TITLE
kurl.sh airgap download doesn't work

### ISSUE THREAD

**Issue by grantmiller** [replicatedhq/kurl#153]
if you click the download airgap installer link on the kurl.sh site:
![airgap download](https://user-images.githubusercontent.com/1041501/71934425-42282900-3159-11ea-9097-34b5b65a4f5f.png)
, you just see an endless spinner: ![spinner](https://user-images.githubusercontent.com/1041501/71934361-1d33b600-3159-11ea-93bf-e5fafa03f936.png)

**Comment by areed** [comment]
Fixed by #160
