### ISSUE TITLE
Is the race condition still happening with ekco?

### ISSUE THREAD

**Issue by evilmonkeyslayer** [replicatedhq/kURL#1591]
As per here: https://kurl.sh/docs/add-ons/ekco#reboot

"The shutdown script may fail to complete because it depends on services running on the node to be available to delete pods, but these services may already be shutting down. To avoid race conditions, manually run the ekco-reboot service's shutdown script prior to proceeding with system shutdown or reboot"

Just aware having to manually run a shutdown script is problematic if you accidentally do something like rebooting the kurl server.

And I noticed this pull request: https://github.com/replicatedhq/kURL/pull/1560

Does that fix it?

**Comment by areed** [comment]
That is a partial fix for the issue, but there are still other conditions that could cause the reboot to hang.

**Comment by evilmonkeyslayer** [comment]
> 
> 
> That is a partial fix for the issue, but there are still other conditions that could cause the reboot to hang.

Thanks, is there any way to not run this manually? Currently trying to get this in use, been trying all sorts of custom systemd services with requires, before etc. None with success so far. Can kurl be safely used without ekco?

**Comment by areed** [comment]
No, kurl cannot be safely used without ekco. In addition to reboot scripts, it provides certificate rotation and some features for recovery after a node is lost.

Kubernetes 1.21 provides a feature for graceful shutdown that's enabled by kurl. This may provide some protection against unexpected restarts, but I've still seen a server get stuck on 1.21 so I'd recommend continuing to use the ekco shutdown script manually when possible.

**Comment by evilmonkeyslayer** [comment]
Just checking up on this, is this still an ongoing issue?

**Comment by areed** [comment]
Yes, the script must still be run before shutdown to safely unmount PVCs.

**Comment by evilmonkeyslayer** [comment]
> Yes, the script must still be run before shutdown to safely unmount PVCs.

Is there a timeline on a fix for this, or is it a gradual kind of thing?

Thanks.

**Comment by areed** [comment]
There's no timeline because there's no known fix.

**Comment by MikaelSmith** [comment]
Could part of getting stuck be that the service doesn't have enough time to perform all shutdowns? Services have a 90s timeout for ExecStop on shutdown.

**Comment by camilamacedo86** [comment]
Hi @evilmonkeyslayer,

This one is very old and is possible that the behaviours are changed in the latest versions.
So, I am closing this one. However, if you check that the latest version still requiring address something related to this topic please feel free to re-open and let us know from the current state what would still missing and what should be done instead. 

Thank you for your attention.
