### ISSUE TITLE
Errors were encountered while processing Kubernetes CNI

### ISSUE THREAD

**Issue by FelipeMiranda** [replicatedhq/kURL#1592]
Distro:
fel@u:/opt/kurl-lab$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"

`curl https://kurl.sh/68ba0d7 | sudo bash`

```
update-initramfs: Generating /boot/initrd.img-5.4.0-72-generic
Errors were encountered while processing:
 ./packages/kubernetes/1.19.10/ubuntu-20.04/kubernetes-cni_0.8.7-00_amd64.deb
 kubelet
An error occurred on line 2313
```

**Comment by camilamacedo86** [comment]
This one is very old and still without interaction to get further information for more than 1 yr. 
So, I am closing this one. However, if you see that still a requirement please feel free to re-open.
