### ISSUE TITLE
I couldn't get preflight-ignore to prevent bail in mustSwapoff in installer

### ISSUE THREAD

**Issue by zt-initech** [replicatedhq/kURL#1674]
I want to run kurl with swap enabled, for testing.

I've tried "preflight-ignore" from https://kurl.sh/docs/install-with-kurl/advanced-options as a command line argument (with airgap) and also I've tried preflightIgnore in yaml to get a bundle with that baked in.

I got the "This application is incompatible with memory swapping enabled" prompt both times. I want to be able to auto-skip this and continue installing. How can I do this?

**Comment by emosbaugh** [comment]
This is not currently possible.

**Comment by camilamacedo86** [comment]
Hi @zt-initech, 

This one is very old. By looking at the doc it has the option:

> curl https://kurl.sh/latest | sudo bash -s host-preflight-ignore

![Screenshot 2022-12-21 at 07 53 37](https://user-images.githubusercontent.com/7708031/208850475-c173ab63-aade-46af-807c-ca2602fe3834.png)

So, I am closing this one but if you see that still a requirement please feel free to re-open. 




<br class="Apple-interchange-newline">
