### ISSUE TITLE
Install script hangs if weave add-on isn't deployed successfully

### ISSUE THREAD

**Issue by fshot** [replicatedhq/kURL#245]
Currently, the default kurl install process attempts to deploy weave, and then continues after applying the weave yaml to the cluster, regardless of whether or not the weave deployment succeeds.

If there are problems with the weave deployment, no error is shown to the user, and the install proceeds to try to install the rook addon, which will likely hang during its `rook_ready_spinner` stage.  This is a problem, because it makes a weave problem look like a rook problem.

The weave add-on should use a similar pattern to the rook add-on, waiting for evidence that the weave deployment was successful, and exiting the install with an error if the deployment doesn't complete within a reasonable timeout period.

The simplest way to reproduce the weave failure is to use the `ip-alloc-range` parameter when running the kurl.sh install script, specifying an ip range that deliberately conflicts with reserved ips.

For example, to reproduce the problem on a GCP instance within the `us-west2` region, you could run ```curl https://kurl.sh/latest | sudo bash -s ip-alloc-range=10.168.0.1/16```

This problem reproduces with the default kurl.sh install config, but should also reproduce with any other kurl config that includes both weave and rook.

**Comment by DevAndrewGeorge** [comment]
Seems this is solvable by simply making a call to the `spinnerPodRunning` [function](https://github.com/replicatedhq/kURL/blob/c2422525b856681d2df60fb04b320bfc7feb7ea4/scripts/common/common.sh#L97) to poll when the [weave DaemonSet's](https://github.com/replicatedhq/kURL/blob/c2422525b856681d2df60fb04b320bfc7feb7ea4/addons/weave/2.5.2/daemonset.yaml) `weave-net-*` pod becomes available; `spinnerPodRunning` being the underlying function which the `rock_read_spinner` [function](https://github.com/replicatedhq/kURL/blob/c2422525b856681d2df60fb04b320bfc7feb7ea4/addons/rook/1.0.4/install.sh#L67) calls.

However, you mention the following: 
> The weave add-on should use a similar pattern to the rook add-on, waiting for evidence that the weave deployment was successful, and exiting the install with an error if the deployment doesn't complete within a reasonable timeout period.

In terms of behaving similarly, the `spinnerPodRunning` function does not actually have a timeout and will hang indefinitely (as you have specified) regardless. It would also be a QoL improvement to have this function return a non-zero to its caller, but adding such logic + any scaffolding necessary (e.g. error checking in the caller, parameterizing a reasonable timeout) may be beyond on the scope of this PR.

**Comment by DevAndrewGeorge** [comment]
For now, I've solved *where* the installer should hang in #246. It seems there's already precedent in [common.sh](https://github.com/replicatedhq/kURL/blob/c2422525b856681d2df60fb04b320bfc7feb7ea4/scripts/common/common.sh#L228) for a spinner with a timeout for arbitrary commands. Seems easy enough to leverage this function for the simple checking of available pods.

As for a reasonable timeout, it seems 120 seconds has become the precedent based on calls to the `spinner_until` function.

**Comment by fshot** [comment]
Thanks, @DevAndrewGeorge -- this is a great first step.  We will add a followup issue to enhance the `pod waiting spinner` behavior.
