### ISSUE TITLE
`getNoProxyAddresses` doesn't exist

### ISSUE THREAD

**Issue by cmcarthur** [replicatedhq/kURL#264]
The latest kurl.sh references a function "getNoProxyAddresses" that does not exist. So, when a customer tries to specify a proxy, the install script fails. See command below highlighting the issue.

```bash
$ curl -sSL https://kurl.sh/latest | grep -n -5 'getNoProxyAddresses'
1827-        if [ -z "$PROXY_ADDRESS" ] && [ "$AIRGAP" != "1" ]; then
1828-            promptForProxy
1829-        fi
1830-
1831-        if [ -n "$PROXY_ADDRESS" ]; then
1832:            getNoProxyAddresses "$PRIVATE_ADDRESS" "$SERVICE_CIDR"
1833-        fi
1834-    fi
1835-
1836-    prompt_airgap_preload_images
1837-}
```

EDIT: example output here:

```
The installer will use network interface 'xxx' (with IP address 'x.x.x.x’)

Does this machine require a proxy to access the Internet? (y/N) y

Enter desired HTTP proxy address: https://proxy-name:8080

The installer will use the proxy at 'https://proxy-name:8080'

./script.sh: line 1832: getNoProxyAddresses: command not found
```

**Comment by dexhorthy** [comment]
@laverya do you know if this has been adressed?

**Comment by RatanVMistry** [comment]
I can see the same issue when I use http_proxy.
I downloaded the latest script and run ./latest http_proxy 
my VM have http_proxy, https_proxy and no_proxy set at ~/.bashrc 
 
I added some extra lines to debug 
![image](https://user-images.githubusercontent.com/20649157/80036463-9e178300-84a6-11ea-8fd5-7a3728999b04.png)

`The installer will use the proxy at 'http://172.16.1.232:8080' (imported from env var 'http_proxy')
The installer will use network interface 'ens5' (with IP address '172.16.2.198')
The installer will use the proxy at 'http://172.16.1.232:8080' (imported from env var 'http_proxy')
I am in Prompts 3rd
./latest: line 1914: getNoProxyAddresses: command not found`

**Comment by dexhorthy** [comment]
@cmcarthur did you ever get a workaround in place for this? Or did you just go straight to airgap?

**Comment by dexhorthy** [comment]
@areed I understand that the PR #463 fixes this -- do you have an ETA on release? Will this ship with a KOTS release or on a separate cadence?

**Comment by areed** [comment]
This wil be in the 1.16 kots release.

**Comment by divolgin** [comment]
@dexhorthy @areed can this issue be closed?

**Comment by areed** [comment]
Yes
