### ISSUE TITLE
Documentation improvement

### ISSUE THREAD

**Issue by chrisbra** [replicatedhq/kURL#2680]
Hi,
I was just recently trying to install kurl using the documentation https://kurl.sh/docs/install-with-kurl/ , so basically: `curl https://kurl.sh/latest | sudo bash`

It failed miserably because my `/var/lib` didn't have 50 GB space free. Then I looked around and found https://kurl.sh/docs/install-with-kurl/advanced-options, so apparently one can use `kurl-install-directory` to specify the install directory. 

What do you mean with ` Re-run the scripts with different flags to change the behavior of the installer.` ? This is totally unclear in the context of shell scripts. For shell-scripts, I would expect either using an environment variable or giving an argument. But what do you mean with specify flags? And even if I would know, how would I set a flag with a special value? That is not a flag anymore then. And most importantly, how to I specify the value to that flag? 

So please, clarify how exactly those flags should be given to the installer and please also provide examples on how to use those flags for the documentation.

Thanks

**Comment by camilamacedo86** [comment]
HI @chrisbra,

It is open for a while and I was looking at the documentation and it seems solved, see:

<img width="910" alt="Screenshot 2023-02-15 at 10 00 40" src="https://user-images.githubusercontent.com/7708031/218996037-264990ee-320e-4fd1-bd68-ab6d62506c89.png">

 The documentation describes how to use the flags. When you call the script you will use `-s` to inform the flag.

Then, you can check that in the reference for each option you will find examples to let you know what values you should inform and how to use it:

<img width="903" alt="Screenshot 2023-02-15 at 10 02 08" src="https://user-images.githubusercontent.com/7708031/218996432-4a652b9a-8b1c-4765-a232-6a6d5bf81613.png">

So, I am closing this one as sorted out. However, if you would like to propose suggestions or you still with questions/concerns about this doc, could you please raise a new issue and let us knows what are you saying and what you would expected instead and why?

Thank you for your contribution and attention.
