### ISSUE TITLE
specifying kurl-install-directory is not honored by the longhorn preflight script

### ISSUE THREAD

**Issue by chrisbra** [replicatedhq/kURL#2681]
As mentioned #2680, apparently I need to set `kurl-install-directory` to make sure to install kurl on a disk with more space. However, longhorn still insists on checking the size of `/var/lib/longhorn`  because it uses a hard-coded value in the `preflight.yml` 
![image](https://user-images.githubusercontent.com/244927/153552323-82d12d58-14ba-4e64-80c1-d3da0766183f.png)

So the installation still fails on my system :(

**Comment by camilamacedo86** [comment]
Hi @chrisbra,

Thank you for raise this issue. 
However, we also would like to share that kURL is moving away from longhorn.

In this way, we would like to recommended adopt Rook or OpenEBS. To better understand the motivations see [here](https://github.com/replicatedhq/kURL/blob/main/docs/arch/adr-002-rook-distributed.md).

**Comment by camilamacedo86** [comment]
Hi @chrisbra,

It is open for a long time ago. Also, we are moving away from longhorn.
In this away, I am closing this one. However, if you see that would still required to address this issue for any reason please let us know and feel free to re-open this one.
