### ISSUE TITLE
can we add flannel to cni plugin option aswell please 

### ISSUE THREAD

**Issue by sairamkrishna222** [replicatedhq/kURL#2774]
Hi, We are actually using kurl for our High availability. can we also have flannel as cni plugin please.

**Comment by trelore** [comment]
Hi @sairamkrishna222 , we've got an internal ticket about the future of CNI addons, I've linked to this issue from that ticket.

Thanks for registering interest in kURL!

**Comment by camilamacedo86** [comment]
Hi @alexanderjophus and @sairamkrishna222, 

This request seems to be addressed already, see https://kurl.sh/:

<img width="1263" alt="Screenshot 2023-02-15 at 10 08 13" src="https://user-images.githubusercontent.com/7708031/218997770-3595b88f-9884-4b8a-83a0-5b0bf7543630.png">

So, I am closing this one. 
However, please feel free to re-open or raise new ones if you see that fits.
