### ISSUE TITLE
node join scripts use the instance IP in HA clusters

### ISSUE THREAD

**Issue by laverya** [replicatedhq/kURL#33]
When creating a node join script for an HA cluster, the master address should be the DNS name for the kube api, not the node IP (when provided). This script should continue to function even if the original master no longer exists.

**Comment by camilamacedo86** [comment]
Hi @laverya,

It is a bug raised more than 3 yrs ago so it is like that got sorted out already or get obsolete.
I am closing this one, however, if you see that still required please feel free to re-open.
