### ISSUE TITLE
Generated passwords contain spaces

### ISSUE THREAD

**Issue by BarryWilliams** [replicatedhq/kURL#3398]
After deploying a cluster with kurl, sometimes passwords contain spaces. I have had this happen to where the space was at the end of the password - which can trick the eye when doing a copy/paste.

![image](https://user-images.githubusercontent.com/8444690/187688449-d92a911a-6acb-4a96-80d3-cebd61f035e7.png)

**Comment by rrpolanco** [comment]
@BarryWilliams The trailing whitespace is _not_ part of the password string itself but part of the print statement [formatting](https://github.com/replicatedhq/kURL/blob/main/addons/prometheus/template/base/install.sh#L107). kURL ensures passwords are generated within [A-Za-z0-9](https://github.com/replicatedhq/kURL/blob/main/addons/prometheus/template/base/install.sh#L90) character class.

**Comment by camilamacedo86** [comment]
Hi @BarryWilliams,

I am closing this one as sorted out based in the above comment. 
However, if you see that is required please feel free to re-open this one.
