### ISSUE TITLE
node join scripts do not include kubeadm token ca hash when generated on additional masters

### ISSUE THREAD

**Issue by laverya** [replicatedhq/kURL#34]
The generated node join script does not include the kubeadm-token-ca-hash parameter when run on a new master node following the destruction of the original master node. For example:

```
To add worker nodes to this installation, run the following script on your other nodes
    curl https://staging.kurl.sh/62906b1/join.sh | sudo bash -s kubernetes-master-address=10.2.131.201 kubeadm-token=1oc3h1.cql0qqc7evfyju16 kubeadm-token-ca-hash= kubernetes-version=1.15.3
```

This prevents new nodes from being joined to the cluster.

**Comment by camilamacedo86** [comment]
Hi @laverya,

It is a bug raised more than 3 yrs ago so it is like that got sorted out already or get obsolete.
I am closing this one, however, if you see that still required please feel free to re-open.
