### ISSUE TITLE
Getting the add worker nodes script with parameters after installation is completed

### ISSUE THREAD

**Issue by liiri** [replicatedhq/kURL#360]
At the end of the installation using kURL we get a nice reference on how to add worker nodes, i.e

```
To add worker nodes to this installation, run the following script on your other nodes
    curl -sSL https://kurl.sh/xxx/join.sh | sudo bash -s ...
```

Can I re-create this script command on demand? If not, would it be possible to plot it to some reference file in the first place during installation script?

**Comment by areed** [comment]
The script can be re-generated by [running the install script again](https://kurl.sh/docs/install-with-kurl/adding-nodes). It's not persisted by default because it includes tokens with a 24 hour lifetime (or 2 hours for masters).
