### ISSUE TITLE
Example preflights does not seems with correct kURL requirements

### ISSUE THREAD

**Issue by camilamacedo86** [replicatedhq/kURL#3734]
**Bug Description**

I did the latest kURL install and check it out with `kubectl preflight https://preflight.replicated.com`. 

**Expected Behavior**

Do not see warnings or errors.
Values described on the check matches with the kURL system requirements: https://kurl.sh/docs/install-with-kurl/system-requirements#minimum-system-requirements

**Steps To Reproduce**

- Into an linux/amd instance run `curl https://kurl.sh/latest | sudo bash`
- Then, run `kubectl preflight https://preflight.replicated.com` to check it out 

**Check its result**

```
Example Preflight Checks

Check PASS
Title: Required Kubernetes Version
Message: Your cluster meets the recommended and required versions of Kubernetes.

------------
Check FAIL
Title: Ingress
Message: Contour ingress not found!

------------
Check PASS
Title: Container Runtime
Message: containerd container runtime was found.

------------
Check PASS
Title: Required storage classes
Message: All good on storage classes

------------
Check PASS
Title: Kubernetes Distribution
Message: KURL is a supported distribution

------------
Check FAIL
Title: Must have at least 3 nodes in the cluster, with 5 recommended
Message: This application requires at least 3 nodes.
URI: https://kurl.sh/docs/install-with-kurl/adding-nodes

------------
Check WARN
Title: Every node in the cluster must have at least 10 GB of memory, with 32 GB recommended
Message: All nodes are recommended to have at least 32 GB of memory.
URI: https://kurl.sh/docs/install-with-kurl/system-requirements

------------
Check PASS
Title: Total CPU Cores in the cluster is 4 or greater
Message: There are at least 4 cores in the cluster

------------
Check PASS
Title: Every node in the cluster must have at least 40 GB of ephemeral storage, with 100 GB recommended
Message: All nodes have at least 100 GB of ephemeral storage.

------------
``` 

**Concerns/PRs to fix**

- [x] Minimal requirement for Memory is 8 and not 10 - PR open to fix it: https://github.com/replicatedhq/troubleshoot/pull/843
- [ ] Contour ingress not found! is not a requirement for kURL - PR open to remove the check : https://github.com/replicatedhq/troubleshoot/pull/840
- [ ] KURL does not seems require 3 nodes - PR to remove the check https://github.com/replicatedhq/troubleshoot/pull/842

**Additional Context**

- a) Do we really need to recommend `32 GB recommended` for the memory check and raise it as warning:

<img width="864" alt="Screenshot 2022-11-15 at 12 44 47" src="https://user-images.githubusercontent.com/7708031/201929104-09f36614-28fa-4ac3-83d8-a99363a1b9a8.png">

PS.: Why we would recommend 32 GB by default?
 
- b) The behaviour of the storage check seems not match with the memory one? In this case we recommend but we do not raise a warning? What should be the expected behaviour when a recommendation is made? Should we raise or not a warning in those scenarios? 

- c) Why we would recommend 100 GB? 

See: 
<img width="863" alt="Screenshot 2022-11-15 at 13 21 18" src="https://user-images.githubusercontent.com/7708031/201929934-06bc22cb-e7e8-4a0f-a26b-8628ac8891c8.png">

**Comment by camilamacedo86** [comment]
Hi @chris-sanders, 

Before, we move forward with both checks ingress (https://github.com/replicatedhq/troubleshoot/pull/840/files) and nodes one (https://github.com/replicatedhq/troubleshoot/pull/842/files)

I would like to clarifies that:
- a) I look at the kurl docs and we do not say for nobody does `kubectl preflight https://preflight.replicated.com`
- b) kURL has many preflight checks indeed for the addons: https://github.com/replicatedhq/kURL/search?q=troubleshoot.sh%2Fv1beta2 

So, I believe that @emosbaugh thoughts are right. It is only an example. However, I think as a user trying to figure out the things I would probably end up doing the same instead of read all docs.

Therefore, maybe the right solution would to be only clarify into its domain `https://preflight.replicated.com` that is just an example and avoid a misunderstanding. (i.e. https://preflight.example.replicated.com). WDYT?

**Comment by chris-sanders** [comment]
It would seem to me that having a url like `preflight.replicated.com` provides a convenient short URL for people to use. I don't know that I see value in providing a subdomain for an example file, at that point just go to the repository. The only team that could make use of `preflight.replicated.com` I think is the kURL team, if that assumption is correct I think what's available at that subdomain can be dictated by the kURL team. If our docs don't use it, and kURL doesn't have a use for it, maybe we deprecate it?

It seems a bit risk to point a subdomain to a simple example file with no clear purpose, Vendors may mistake the URL for more than it is.

**Comment by emosbaugh** [comment]
I only see this url in the troubleshoot docs, not kurl

https://www.google.com/search?q=%22preflight.replicated.com%22&rlz=1C5CHFA_enUS979US979&oq=%22preflight.replicated.com%22&aqs=chrome..69i57.634j0j7&sourceid=chrome&ie=UTF-8

**Comment by chris-sanders** [comment]
If this isn't being used by kURL I suggest we just close this issue. I just want to check that the install script isn't using the URL even if it isn't documented on kurl.sh. @emosbaugh if you're confident kURL doesn't use this URL I think we can close this as a no-op.

**Comment by camilamacedo86** [comment]
Yes, I think we can safely close this one. 
Thank you for the attention.
