### ISSUE TITLE
More user task oriented docs

### ISSUE THREAD

**Issue by MikaelSmith** [replicatedhq/kURL#404]
A task I've found error-prone and also poorly documented is decommissioning worker/master nodes in a cluster. It'd be really helpful to have some kurl-specific docs on https://kurl.sh/docs.

Also rebooting worker/master nodes.

**Comment by camilamacedo86** [comment]
Hi @MikaelSmith,

Thank you for raising this one. I am not sure if I could properly understand your request.
However, it is very old so it might be addressed already.

In. this way, I am closing this one but if you see that we still needing to address this topic in the docs please feel free to re-open this one. Also, if that be the case, could you please provide a further explanation about that?  

Thank you for your attention and time.
