### ISSUE TITLE
Support for non-Docker environments

### ISSUE THREAD

**Issue by marccampbell** [replicatedhq/kURL#406]
Let's track adding support for operating systems and environments that don't have Docker. There are various options being discussed (containerd, podman) and this issue can be used to track the overall progress.

Once completed, this will enable:
- Any operating system that doesn't have Docker
- Building installers without a docker plugin (even for OS with docker support)
- CentOS 8
- RHEL 8

**Comment by areed** [comment]
Kubelet requires a container runtime daemon listening on a unix socket. Containerd and CRI-O both have that, but podman does not, although it's possible the new HTTP API coming in podman 2.0 will work.

The other issue is loading images from an airgap bundle. With podman the docker CLI commands in the kURL install scripts work if you also install the `podman-docker` package, but for containerd the scripts will need to use `ctr image import`.

**Comment by areed** [comment]
It is possible to get docker running on CentOS 8 with a couple of manual steps.

**Comment by marccampbell** [comment]
@areed Thanks for the extra info.

It sounds like the best non-docker solution available today (before Podman 2) is to support the containerd CRI? CentOS 8 support would come, but that’s slightly different from this issue, which is to support non-Docker environments for the installer.

**Comment by areed** [comment]
Yes, containerd would be simpler than cri-o because containerd has the ctr CLI for loading images but for cri-o we'd need to install skopeo separately and push all images to the local registry.

**Comment by marccampbell** [comment]
Closing as we now have containerd support
