### ISSUE TITLE
Kurl install .sh is giving eror

### ISSUE THREAD

**Issue by bakudih** [replicatedhq/kURL#4095]

**Comment by camilamacedo86** [comment]
Hi @bakudih,

Could you please provide more details? Example:
- What is the error faced?
- What is the install used? 
= Could you provide the link used to do the install?

**Comment by camilamacedo86** [comment]
Hi @bakudih,

You open another issue with this one: https://github.com/replicatedhq/kURL/issues/4096.

So, I am closing this in favor of the other this one seems to be duplicated.
