### ISSUE TITLE
Kurl install .sh is giving errorW0214 15:47:58.603271   22635 common.go:84] your configuration file uses a deprecated API spec: "kubeadm.k8s.io/v1beta2". Please use 'kubeadm config migrate --old-config old.yaml --new-config new.yaml', which will write the new, similar spec using a newer API version. W0214 15:47:58.604290   22635 common.go:84] your configuration file uses a deprecated API spec: "kubeadm.k8s.io/v1beta2". Please use 'kubeadm config migrate --old-config old.yaml --new-config new.yaml', which will write the new, similar spec using a newer API version. nodeRegistration.name: Invalid value: "vision_ason_vm26": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*') To see the stack trace of this error execute with --v=5 or higher An error occurred on line

### ISSUE THREAD

**Issue by bakudih** [replicatedhq/kURL#4096]

**Comment by camilamacedo86** [comment]
Hi @bakudih,

Part of the title of this issue shows an issue:

> Invalid value: "vision_ason_vm26": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*') To see the stack trace of this error execute with --v=5 or higher An error occurred on line [1 hour ago](https://github.com/replicatedhq/kURL/issues/4096#event-8513917082)

However, we need further information to try help you out:

- Please, provide the kURL logs which are under /var/log/kurl. Could you please add them here?
- Please, provide the link used to the install
- Please, let us know if it is a new install or if it is an upgrade
- Also, can you please share the support bundle? It probably was created when the error was faced if say Y I want report the issue. Or you can see https://community.replicated.com/t/kurl-how-can-i-generate-a-support-bundle-when-my-kubernetes-cluster-is-down/911 and attached here the result.
