### ISSUE TITLE
Allow configuring external ElasticSearch cluster to be used by fluentd

### ISSUE THREAD

**Issue by divolgin** [replicatedhq/kURL#447]
Right now fluentd config is hardcoded to use `elasticsearch.logging.svc.cluster.local` and there is no way to change that via the install script.

**Comment by mzaneri** [comment]
solved with https://github.com/replicatedhq/kURL/pull/468

**Comment by dexhorthy** [comment]
@mzaneri are there any docs for this yet? I see only a few flags here 

https://kurl.sh/docs/add-ons/fluentd
