### ISSUE TITLE
Calling 'kubeadm join --ignore-preflight-errors=all' suppresses errors concerning etcd cleanup

### ISSUE THREAD

**Issue by MikaelSmith** [replicatedhq/kURL#457]
According to https://github.com/kubernetes/kubeadm/issues/2095, using `--ignore-preflight-errors=all` suppresses errors that should help with ensuring you don't try to start a new etcd instance with a dirty data directory. Why is that option used?

**Comment by camilamacedo86** [comment]
Hi @MikaelSmith,

Thank you for raise this one. It is old and I could find in the docs the following option:

![Screenshot 2022-12-21 at 08 13 25](https://user-images.githubusercontent.com/7708031/208853861-cfcf6e90-3dd9-4185-ba23-ff7b2c97258c.png)

See: https://kurl.sh/docs/install-with-kurl/advanced-options

In this way, I am closing this one but if you think that should be kept open please feel free to re-open. In this case, please let us know what would be the reason for we check how can we address this one. 

Thank you.
