### ISSUE TITLE
Pre-install checks

### ISSUE THREAD

**Issue by MikaelSmith** [replicatedhq/kURL#499]
Running through installs on different system configurations, we've found a number of stumbling blocks that required digging deeply into the install to resolve. A few preflight checks before the install would help avoid these. We found we needed:
- sufficient CPUs to schedule all the pods; for our install that was >2, but it would vary based on installer config
- sufficient memory to schedule all pods; our install needed at least 4 GB memory (would also vary based on installer config)
- sufficient disk space in `/var` for container images and logs, and `/opt` for rook storage; this again can vary but probably safe to say at least 10s of GBs for each
- OS version; for example trying to install on CentOS 7.2 ran into issues with devicemapper

It'd be helpful to be able to define preflights that the install validates, or have some defined for us based on the configured addons.

**Comment by ccaum** [comment]
+1 to this. This is would very helpful for our customers and prevent them from hitting a cliff later in the installation process.

**Comment by abottchen** [comment]
Adding to the list here, it would be good if the checks included making sure the network ranges that are going to be used for weave are non-routable.  

We have had several customers inadvertently end up with installations that were routing k8s and weave network traffic off the machines to network devices that could not sort out routing it back.  This manifested as installations that just had intermittent network problems, which was hard to debug after the fact.

**Comment by MikaelSmith** [comment]
Host preflights seem to be in Troubleshoot and kURL, but I haven't found any documentation of them yet.

**Comment by emosbaugh** [comment]
We are currently working on adding the ability to customize host preflights in the kurl spec.

**Comment by camilamacedo86** [comment]
Hi @MikaelSmith,

This one is very old which means that a lot of changes were addressed in the latest releases. Also, based on the @emosbaugh comment seems that your request is addressed already.

So, I am closing this one. However, please feel free to re-open if you see that we still needing to address what do you requested here. In this case, please let us know from the latest version what still missing to get done.

Thank you a lot for your attention and time.
