### ISSUE TITLE
proxy check uses non-kurl URL

### ISSUE THREAD

**Issue by laverya** [replicatedhq/kURL#512]
https://github.com/replicatedhq/kURL/blob/a18c2e2a488c5f28dc6504b84f38bf73f0c605a8/scripts/common/proxy.sh#L27
https://github.com/replicatedhq/kURL/blob/a18c2e2a488c5f28dc6504b84f38bf73f0c605a8/scripts/common/proxy.sh#L67

It would be great if this could hit something like `k8s.kurl.sh/latest` to keep the number of required URLs down.

**Comment by emosbaugh** [comment]
This seems to be resolved, closing.
