### ISSUE TITLE
[testgrid] timeout and fail

### ISSUE THREAD

**Issue by marccampbell** [replicatedhq/kURL#548]
when a test case runs too long, we should timeout and fail (upload the logs, etc)

**Comment by camilamacedo86** [comment]
Hi @marccampbell,

Thank you for raising it. This one is old and seems done already. See: 

![Screenshot 2022-12-21 at 08 31 21](https://user-images.githubusercontent.com/7708031/208857393-285d5cba-7ad4-4f94-9d99-ce6ddfe337c7.png)

In this way, I am closing it. However, please feel free to re-open if you see that we still have this need and let us know what in your POV is missing.
