### ISSUE TITLE
kotadm addon: kurl-proxy: button styles looking very off

### ISSUE THREAD

**Issue by dexhorthy** [replicatedhq/kURL#580]
See screenshot -- this has been spotted in a number of environments, below is from running 

```
curl https://k8s.kurl.sh/sentry-pro | sudo bash
```

<img width="1385" alt="Screen Shot 2020-06-29 at 9 02 27 AM" src="https://user-images.githubusercontent.com/3730605/86015587-60bffc00-b9e7-11ea-9350-c7769593ad9b.png">

**Comment by jgruica** [comment]
resolved by: https://github.com/replicatedhq/kots/pull/708
