### ISSUE TITLE
Add support for weave 2.6.5

### ISSUE THREAD

**Issue by cmcarthur** [replicatedhq/kURL#590]
Weave 2.6.5 is a bugfix release. In particular, it fixes one nasty bug where weave will CrashLoopBackOff if ipv6 is disabled on the host. This is preventing installation of kurl at a company that disables ipv6 out of the box on all hosts.

https://github.com/weaveworks/weave/releases/tag/v2.6.5

**Comment by markpundsack** [comment]
2.6.5 is now supported.
