### ISSUE TITLE
k8s controller manager and scheduler should not listen on insecure ports

### ISSUE THREAD

**Issue by emosbaugh** [replicatedhq/kURL#637]
```
$ sudo netstat -tulpn | grep 1025
tcp        0      0 127.0.0.1:10257         0.0.0.0:*               LISTEN      16098/kube-controll
tcp        0      0 127.0.0.1:10259         0.0.0.0:*               LISTEN      16141/kube-schedule
tcp6       0      0 :::10250                :::*                    LISTEN      16523/kubelet
tcp6       0      0 :::10251                :::*                    LISTEN      16141/kube-schedule
tcp6       0      0 :::10252                :::*                    LISTEN      16098/kube-controll
tcp6       0      0 :::10256                :::*                    LISTEN      17201/kube-proxy
```

https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler/

can add this to the `kubeadm/v1beta2.ClusterConfiguration`

```
controllerManager:
  extraArgs:
    port: '"0"'
scheduler:
  extraArgs:
    port: '"0"'
```

**Comment by austinchambers** [comment]
ch25481

**Comment by austinchambers** [comment]
Per https://github.com/kubernetes/kubernetes/pull/92720, this will not be the default behavior in k8s 1.19. Thus, we have a decision on how kURL handles this change. 

There are two cases:
1. We do nothing. In this case, it makes sense kURL to generally go from implicit insecure (1.18) to implicit secure (1.19). (We may also add an option to explicitly to go against default, if there are exceptions needed)
2. When we introduce 1.19 support with kURL, we may choose to preserve the insecure port behavior. Thus, we may choose to automatically go from implicit insecure port to explicit insecure port in 1.19 just to keep the status quo. If we go this route, we’ll definitely add an option to override this and explicitly use a secure port.

In either case, a consumer of kURL has the option to apply the above patch to `kubeadm/v1beta2.ClusterConfiguration` on k8s 1.16-1.18. If the above patch is applied, then the consumer needs to do the following on upgrade to 1.19 or later: 
1. If we took option #1 above, then nothing needs to change on upgrade to 1.19. The kURL cluster will continue to be implicit secure. 
2. If we took option #2 above, then the kURL installer should be updated when changing k8s version to 1.19 to also explicitly include a new parameter to indicate an explicit and secure port. This way, the secure port remains intact.

**Comment by yasserg** [comment]
@austinchambers can you please provide the detailed instructions for us to apply the suggested change to kubeadm/v1beta2.ClusterConfiguration (where is this config). We will need to do that in the meantime.

**Comment by emosbaugh** [comment]
To workaround this issue until it is fixed in kurl:

1. install kurl on the first master

1. edit `/opt/replicated/kubeadm.conf`. add the following to the `kubeadm/v1beta2.ClusterConfiguration` doc: 
   ```
   controllerManager:
     extraArgs:
       port: '"0"'
   scheduler:
     extraArgs:
       port: '"0"'
   ```

   In the default kubeadm.conf there is already a `controllerManager: {}` property in the doc which must be replaced.

1. run `kubeadm init --ignore-preflight-errors=all --config /opt/replicated/kubeadm.conf`

Note that the change will be reverted when re-running `curl kurl.sh | bash`

**Comment by austinchambers** [comment]
So a possible scenario is: 
1. Customer makes the above modification to their kubeadm.conf for current kURL package of vendor software. Port is secured. 
2. k8s 1.19 comes out, where default is to use secure ports. 
3. Vendor modifies their kurlspec yaml to explicitly use 1.19 (and possibly setting a special param as well, depending on which of the above approaches we take). 
4. Customer re-runs the kURL installer for the new package with 1.19 support. This effectively removes the above workaround. However, since they are using k8s 1.19, then the port will remain secure.

**Comment by emosbaugh** [comment]
closing this as it has been fixed in later versions of kubernetes
