### ISSUE TITLE
Metrics Server as Addon or Core Component

### ISSUE THREAD

**Issue by nikogura** [replicatedhq/kURL#799]
Kubernetes Resources such as Horizontal Pod Autoscalers do not work without the Metrics Server. 

Can we get the Metrics Server included as an addon if not a core component?

The project makes the k8s resources available as a single yaml: https://github.com/kubernetes-sigs/metrics-server/releases

**Comment by emosbaugh** [comment]
Thanks for the contribution! Closing

https://github.com/replicatedhq/kURL/pull/810
