### ISSUE TITLE
Upgrade script gets stuck when pods use eviction policies

### ISSUE THREAD

**Issue by MikaelSmith** [replicatedhq/kURL#817]
We have eviction policies in place for pods, including some - postgres - that aren't supposed to be evicted.
```
evicting pod "postgres-0"
error when evicting pod "postgres-0" (will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget.
...
```

[Kubernetes 1.18](https://v1-18.docs.kubernetes.io/docs/setup/release/notes/) added `disable-eviction` as an option for `kubectl drain`. When upgrading to 1.18 or newer, `kubectl drain` should use that option to ignore PodDisruptionBudgets.

**Comment by dexhorthy** [comment]
expected behavior: during an upgrade, it should be fair to evict them. right now this requires manual intervention by the customer, they'd have to manually delete the pod.

As a short term measure, could possible remove the eviction policy.

@MikaelSmith do things break when this pod gets rescheduled?

**Comment by MikaelSmith** [comment]
Not really, just have downtime while the pod is rescheduled because it's a single instance database.

**Comment by MikaelSmith** [comment]
I'm testing out a change for this. I have two questions:
- will kubectl be upgraded before running `kubernetes_drain`? Looks like no, so this will only be usable when upgrading from an existing 1.18 or later instance.
- when upgrading from Kubernetes 1.17.13 to 1.18.10, it used kubeadm and didn't call `kubernetes_drain`. That seems to have cleanly upgraded but didn't end up draining any pods. That seems preferable; why isn't this approach used for patch upgrades?

**Comment by MikaelSmith** [comment]
Turns out it doesn't actually get stuck, it just had a long timeout. Timeout has been reduced to 2 minutes. I consider this closed; we'll just note it in documentation.
