### ISSUE TITLE
requireRootUser exit 0 regardless of the current user

### ISSUE THREAD

**Issue by amiraliucsc** [replicatedhq/kURL#855]
There are multiple places that function "requireRootUser" is called. This function currently has not been implemented and it returns 0 regardless of the current user. 

Actual behavior should be checking the current user and return 1 (false) if the user is not 0 otherwise it can returns 0. 

The function is used in different places:
- scripts/join.sh
- scripts/upgrade.sh
- scripts/common/preflights.sh

**Comment by camilamacedo86** [comment]
Hi @amiraliucsc, 

This one is very old and it seems like sorted out for the latest releases. 
In this away, I am closing this issue. However, if you see that still required after check the latest version please feel free to re-open this one and let us know more about.

Thank you for your collaboration.
