### ISSUE TITLE
Generate install.sh without using kurl.sh UI

### ISSUE THREAD

**Issue by nerellam** [replicatedhq/kURL#903]
HI,

If I have to generate installer without using kurl.sh website, how do I do that, I couldn't find any documentation regarding the same. can you please share the steps for the same like commands to execute

**Comment by areed** [comment]
If you write your spec in a file named "installer.yaml" then you could use this command, which will return the url for your installer:

```
curl -X POST -H "Content-Type: text/yaml" --data-binary "@installer.yaml" https://k8s.kurl.sh/installer
```

**Comment by nerellam** [comment]
thanks for your reply @areed but that's not my original question, i don't want to take dependency on https://k8s.kurl.sh because it's not opensource, I just require an opensource tool through which an onprem kubernetes cluster can be setup easily, kurl looks interesting for that use case.

Can you share instructions for generating the installer through the code that has been open-sourced

**Comment by damianoneill** [comment]
@areed @nerellam  this is an interesting question, was there any followup to this?

**Comment by emosbaugh** [comment]
Kurl.sh source code is available here https://github.com/replicatedhq/kurl.sh

**Comment by camilamacedo86** [comment]
The questions raised here shows sorted out.
So, I am closing this one but if you see that it should be kept open, please feel free to re-open.

Thank you.
