### ISSUE TITLE
testgrid candidates

### ISSUE THREAD

**Issue by dexhorthy** [replicatedhq/kURL#944]
I find myself using these two often in a lab environment to bootstrap a minimal cluster. One seems to fail pretty consistently (only difference is docker vs containerd -- `containerd+openebs+minio` doesn't seem to get a healthy minio up on U18)

- https://kurl.sh/2e21f57 w/ docker
- https://kurl.sh/de44872 w/ containerd

**Comment by camilamacedo86** [comment]
Hi @dexhorthy,

This bug has more than 2 yrs and is very likely to be sorted out in the latest.
So, I am closing this one but if you see that it still a problem please feel free to re-open this one. 

Thank you for your attention and time.
